# -*- coding: utf-8 -*-
"""CERC-Eicker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiChVBRL35OY27BtC87t9dYmWfaQ8Nct
"""

# Commented out IPython magic to ensure Python compatibility.
# For Soroush
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive/My\ Drive

# Extract the data from the .gml file

import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np

tree = ET.parse('SO06_2013.gml')
root = tree.getroot()

ns = {'bldg': "http://www.opengis.net/citygml/building/1.0",
       'gml': "http://www.opengis.net/gml"}

len(root.findall(".//{http://www.opengis.net/citygml/1.0}cityObjectMember"))
# This is the total number of the buildings in this file.

buildingList = [[[], [], []] for i in range(666)];
buildingCount = 0;

def chunker(seq, size):
    return (seq[pos:pos + size] for pos in range(0, len(seq), size))

for buildingElement in root.findall(".//{http://www.opengis.net/citygml/1.0}cityObjectMember", ns):
  for surfaceElement in buildingElement.findall(".//{http://www.opengis.net/citygml/building/1.0}GroundSurface", ns):
    for polygon in surfaceElement.findall(".//{http://www.opengis.net/gml}posList", ns):
      buildingList[buildingCount][0].append(list(chunker(tuple(map(float, polygon.text.split())), 3)))
  buildingCount += 1

buildingCount = 0;
for buildingElement in root.findall(".//{http://www.opengis.net/citygml/1.0}cityObjectMember", ns):
  for surfaceElement in buildingElement.findall(".//{http://www.opengis.net/citygml/building/1.0}WallSurface", ns):
    for polygon in surfaceElement.findall(".//{http://www.opengis.net/gml}posList", ns):
      buildingList[buildingCount][1].append(list(chunker(tuple(map(float, polygon.text.split())), 3)))
  buildingCount += 1

buildingCount = 0;
for buildingElement in root.findall(".//{http://www.opengis.net/citygml/1.0}cityObjectMember", ns):
  for surfaceElement in buildingElement.findall(".//{http://www.opengis.net/citygml/building/1.0}RoofSurface", ns):
    for polygon in surfaceElement.findall(".//{http://www.opengis.net/gml}posList", ns):
      buildingList[buildingCount][2].append(list(chunker(tuple(map(float, polygon.text.split())), 3)))
  buildingCount += 1

# Convert each polygon float list into a pandas Data frame, containing n by d matrices, n being the geo-coordinates, and d being the number of dimension (3, in this case)
# newList = [pd.DataFrame(np.array(polygon).reshape(-1, 3), columns= list("xyz")) for polygon in newList]
# The above line is NOT APPLICABLE AS OF NOW!

import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from matplotlib.colors import ListedColormap
import shapely
from shapely.geometry import Polygon, MultiPolygon
from shapely.ops import cascaded_union, unary_union

for building in buildingList:
        for surfaceElement in building:
                for polygon in surfaceElement:
                        if (len(polygon) < 3):
                          print ("DIRTY DATA!\n")
                          surfaceElement.remove(polygon)

for building in buildingList:
        for surfaceElement in building:
          for i in range(len(surfaceElement)):
            surfaceElement[i] = Polygon(surfaceElement[i])

def extract_poly_coords(geom):
    if geom.type == 'Polygon':
        exterior_coords = geom.exterior.coords[:]
        interior_coords = []
        for interior in geom.interiors:
            interior_coords += interior.coords[:]
    elif geom.type == 'MultiPolygon':
        exterior_coords = []
        interior_coords = []
        for part in geom:
            epc = extract_poly_coords(part)  # Recursive call
            exterior_coords += epc['exterior_coords']
            interior_coords += epc['interior_coords']
    else:
        raise ValueError('Unhandled geometry type: ' + repr(geom.type))
    return {'exterior_coords': exterior_coords,
            'interior_coords': interior_coords}

roofSurfaceMaximumZCoordinatePerPolygonList = list()
for building in buildingList:
  temporaryZCoordinateForOnePolygonList = list()
  for t in extract_poly_coords(unary_union(building[2]))['exterior_coords']:
    temporaryZCoordinateForOnePolygonList.append(t[2])
  zMax = max(temporaryZCoordinateForOnePolygonList)
  roofSurfaceMaximumZCoordinatePerPolygonList.append(zMax)

groundSurfaceMinimumZCoordinatePerPolygonList = list()
for building in buildingList:
  temporaryZCoordinateForOnePolygonList = list()
  for t in extract_poly_coords(unary_union(building[0]))['exterior_coords']:
    temporaryZCoordinateForOnePolygonList.append(t[2])
  zMin = min(temporaryZCoordinateForOnePolygonList)
  groundSurfaceMinimumZCoordinatePerPolygonList.append(zMin)

differenceList = list()
for i in range(len(groundSurfaceMinimumZCoordinatePerPolygonList)):
  differenceList.append(roofSurfaceMaximumZCoordinatePerPolygonList[i] - groundSurfaceMinimumZCoordinatePerPolygonList[i])

groundSurfaceCoordinatesList = list()
for building in buildingList:
  groundSurfaceCoordinatesList.append(extract_poly_coords(unary_union(building[0]))['exterior_coords'])

finalGroundSurfaceCoordinatesList = list()
for groundSurface in groundSurfaceCoordinatesList:
  finalGroundSurfaceCoordinatesList.append([(x[0], x[1]) for x in (groundSurface)])

!pip install geomeppy

from geomeppy import IDF

IDF.setiddname("Energy+.idd")

idf = IDF("Montreal.idf")

!ls

idf.epw = "USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"

idf.set_default_constructions()

idf.set_wwr(0.6)

idf.run()
